---
- name: Проверить и создать пользователя на удаленных серверах
  hosts: "{{ target_group }}"  # Группа из переменной
  become: yes
  vars_prompt:
    - name: username
      prompt: "Введите имя пользователя для создания"
      private: no
    - name: ssh_key
      prompt: "Введите SSH-ключ для пользователя"
      private: no
    - name: grant_sudo
      prompt: "Добавить sudo права? (y/n, по умолчанию n)"
      private: no
      default: "n"
    - name: password
      prompt: "Введите пароль для пользователя"
      private: yes
      confirm: yes  # Требует подтверждения пароля

  tasks:
    - name: Проверить существование пользователя
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
      check_mode: yes
      register: user_check

    - name: Создать пользователя, если его нет
      ansible.builtin.user:
        name: "{{ username }}"
        state: present
        create_home: yes
        shell: /bin/bash
        password: "{{ password | password_hash('sha512') }}"  # Хешируем пароль
      when: user_check.changed

    - name: Создать директорию .ssh
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'
      when: user_check.changed

    - name: Добавить SSH-ключ для пользователя
      ansible.builtin.copy:
        content: "{{ ssh_key }}\n"
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'
      when: user_check.changed

    - name: Добавить пользователя в группу sudo (если требуется)
      ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        append: yes
      when:
        - user_check.changed
        - grant_sudo == "y"

    - name: Сообщить, если пользователь уже существует
      ansible.builtin.debug:
        msg: "Пользователь {{ username }} уже существует"
      when: not user_check.changed

    - name: Сообщить о результате создания пользователя
      ansible.builtin.debug:
        msg: "Пользователь {{ username }} создан успешно | Sudo права: {{ 'предоставлены' if grant_sudo == 'y' else 'не предоставлены' }}"
      when: user_check.changed
