---
- name: Удаление пользователя из системы Ubuntu
  hosts: "{{ target_group }}"  # Группа из переменной
  become: yes
  vars:
    target_group: "{{ target_group }}"  # Группа из переменной
  vars_prompt:
    - name: username
      prompt: "Введите имя пользователя для удаления:"
      private: no
    - name: remove_home
      prompt: "Удалить домашнюю директорию? (yes/no):"
      default: "no"
      private: no

  tasks:
    - name: Проверка существования пользователя
      ansible.builtin.user:
        name: "{{ username }}"
        state: absent
        remove: "{{ remove_home == 'yes' }}"
      register: user_check

    - name: Вывод результата операции
      ansible.builtin.debug:
        msg: "Пользователь {{ username }} успешно удалён из серверов группы {{ target_group }}"
      when: user_check.changed

    - name: Удаление пользователя из группы sudo (если был)
      ansible.builtin.user:
        name: "{{ username }}"
        groups: sudo
        state: absent
        append: no
      when: user_check.changed

    - name: Очистка crontab пользователя
      ansible.builtin.cron:
        name: "all_user_cron"
        user: "{{ username }}"
        state: absent
      when: user_check.changed
